"""nuevos campos email, password

Revision ID: 18af28f98efb
Revises: 05287d82478d
Create Date: 2026-02-03 21:51:57.931696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18af28f98efb'
down_revision = '05287d82478d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
